# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '2'
  Minor: '0'
  Patch: '1'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Dotnet restore'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration debug'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    packagesToPack: '$(solution)'
    versioningScheme: byPrereleaseNumber
    zipAfterPublish: true
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
  inputs:
      nuGetServiceConnections: 'nuget-connection'

# - task: DotNetCoreCLI@2
#   displayName: 'Dotnet publish'
#   inputs:
#     command: 'publish'
#     publishWebProjects: true
#     zipAfterPublish: true

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    includeNuGetOrg: true
    packagesToPush: 'D:/a/1/s/src/bin/**/*.zip'
    #packagesToPush: 'D:/a/1/s/src/bin/**/*.zip;!D:/a/1/s/src/bin/**/*.symbols.zip'
    vstsFeed: aishwaryasohani
    publishVstsFeed: aishwaryasohani 
    

# - task: NuGetCommand@2
#   displayName: 'NuGet push'
#   inputs:
#     command: push
#     feedsToUse: 'select'
#     nuGetFeedType: internal
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.zip;!$(Build.ArtifactStagingDirectory)/**/*.symbols.zip'
#     versioningScheme: byPrereleaseNumber
#     vstsFeed: aishwaryasohani
#     publishVstsFeed: aishwaryasohani
#     majorVersion: '$(Major)'
#     minorVersion: '$(Minor)'
#     patchVersion: '$(Patch)'
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'